### ISSUE TITLE
您好，MTCNN infer运行的时候报错了~

### ISSUE THREAD

**Issue by yangye19960922** [yeyupiaoling/PaddlePaddle-MTCNN#1]
老师您好，我最近在学习使用pdpd做CV方向，复现您代码结果的时候，在调用第二个模型的时候报错了，请问是怎么回事呀？
![image](https://user-images.githubusercontent.com/36871131/69203280-dc6ae800-0b7e-11ea-9e18-ca93c0e08e76.png)
![image](https://user-images.githubusercontent.com/36871131/69203302-e8ef4080-0b7e-11ea-92a4-13d06f444c5c.png)

**Comment by Baishi03** [comment]
您好，您的图片失效了，看不到。我最近也在复现作者的代码，发现train/infer.py，报错如下：
Traceback (most recent call last):
  File "PaddlePaddle-MTCNN/train/infer.py", line 238, in <module>
    boxes_c, landmarks = infer_image(image_path)
  File "PaddlePaddle-MTCNN/train/infer.py", line 223, in infer_image
    print(boxes_c.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
您有经历这个错误吗？知道怎么解决吗？

**Comment by Baishi03** [comment]
看到你的图片了，错误和我的一样，笑
哥们儿你解决了吗？

**Comment by Baishi03** [comment]
我在infer文件那里进行了改动，只用pnet进行了预测。发现其实是在pnet就出现了错误。
![image](https://user-images.githubusercontent.com/39240051/77174469-1089f180-6afc-11ea-8e86-fcf5823abee6.png)
所有的框都划在了最左侧，再往后计算一下IOU就全为空了。
故为boxes_c=None导致AttributeError: 'NoneType' object has no attribute 'shape'
