### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by shuteng123** [yeyupiaoling/PaddlePaddle-MTCNN#7]
老师您好 我在飞浆平台看到您的一个开源项目，基于MTCNN的一个多人脸信息点定位，我按照您的项目流程训练好效果比较的差 但是我看您的结果图效果很好 请问老师我这个应该如何去让他获得一个更好的结果呀

**Comment by yeyupiaoling** [comment]
这么久应该解决了吧，如果需要再开
